[application]
name = "tauri-dioxus-todo"
default_platform = "web"
out_dir = "dist"
asset_dir = "public"

[web.app]
title = "Tauri + Dioxus - TODO App"

[web.watcher]
reload_html = true
watch_path = ["src", "public"]

[web.resource]
style = []
script = []

[web.resource.dev]
style = []
script = []
